# Generated by Django 6.0 on 2026-01-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boooking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.hotelimage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.hotelimage'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='country_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.city'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service_en',
            field=models.ManyToManyField(null=True, to='Boooking_app.service'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service_ru',
            field=models.ManyToManyField(null=True, to='Boooking_app.service'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='hotel_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.hotel'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
