# Generated by Django 6.0 on 2026-01-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boooking_app', '0002_booking_hotel_en_booking_hotel_ru_city_city_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='room_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.room'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.room'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='country_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Boooking_app.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_list', to='Boooking_app.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_list', to='Boooking_app.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_list', to='Boooking_app.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='Boooking_app.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='Boooking_app.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='Boooking_app.country'),
        ),
    ]
